"""WF-07 / B-02: the row that says "regenerate before sending" can regenerate.

The affordance invariant's own first founding instance, quoted verbatim in
`.claude/agents/auditor.md` - *"the Deliverables table says 'regenerate before
sending' with no regenerate control"*. It stood as an open High for the whole
life of the register that names it, and on 21 August 2026 nine client-facing
comparison documents for a live client walked into it: the WF-75 adopt pass
(`08f663d`) gave every orphan on disk a row, and the nine recovered
`www-acme-com-au-comparison-client-2026-08-17-*` documents carry
`renderer_version` NULL, which `client_reports()` renders as `unknown` and this
screen renders as an instruction the table has no verb for.

**Why the branch had to be painted before it could be guarded.** The rendered
sweep reaches `#/sites/{site}/reports`, so the table is covered - but the
fixture's only deliverable is generated by `POST /api/reports` at the current
`RENDERER_VERSION`, so `renderer` is `current` and neither the `superseded` nor
the `unknown` branch has ever been drawn in this suite's life. Listed is not
painted; DISCIPLINE rule 4. Each live clause below amends the *stored*
`renderer_version` rather than arranging a screen state, for the same reason
`test_heading_fault.py` un-places a stored finding: the case rendered is then a
real row the server built, not one this file invented.

**Regenerating spends nothing**, which is why the control carries no
`SpendMark` and needs no confirmation - `clauditseo/reporting/generate.py`
reaches no provider (`providers_failing` and `providers_answering` are read out
of stored evidence), and `test_a11y_rendered.py`'s own fixture says it outright:
"A deliverable needs no model". Marking a control that does not spend is what
`e979b1c` reverted `711557e` for.

**The `file missing` branch is deliberately out of scope here.** A row whose
file has been moved also states something the operator cannot act on, but a
regeneration produces a *new* document with a new id and leaves that row as
broken as it was - a different remedy, and one worth deciding on its own rather
than absorbing into this one.
"""

from __future__ import annotations

import re
import sqlite3

import pytest

from clauditseo import axe
from clauditseo.reporting.render import RENDERER_VERSION
from tests.test_a11y_rendered import DIST, served  # noqa: F401  (reused fixture)
#: The one owner of this project's contrast arithmetic, reused rather
#: than re-derived: a second implementation of the sRGB luminance
#: formula is how two registers come to report different ratios for one
#: pair, which is the defect `.confirmed-source` shipped under.
from tests.test_dashboard_a11y import AA_TEXT, contrast


#: The two conditions the browser clauses need, copied from
#: `test_a11y_rendered.py` for the same reason `test_heading_fault.py` copies
#: them: the same built bundle and the same browser, applied per test so a
#: module-level mark cannot take a static clause with it.
def live(fn):
    fn = pytest.mark.skipif(
        not (DIST / "index.html").is_file(),
        reason="dashboard not built (npm run build in dashboard/)")(fn)
    return pytest.mark.skipif(
        not axe.available(),
        reason="needs clauditseo[render] and `playwright install chromium`")(fn)


@pytest.fixture()
def browser_page():
    from playwright.sync_api import sync_playwright

    with sync_playwright() as p:
        browser = p.chromium.launch()
        pg = browser.new_page(viewport={"width": 1280, "height": 720})
        try:
            yield pg
        finally:
            browser.close()


#: Located by the header the Deliverables table alone carries, not by
#: `table.findings` - the reports screen renders three tables and picking the
#: first would be a guard that passed by looking at the wrong one. Returns
#: `None` when the table is absent, so "the card did not render" cannot read as
#: "the control is missing".
#:
#: **Compared upper-cased, and that is not fussiness.** The first version of
#: this matched the source's own `Still current?` and found nothing on a screen
#: that was rendering the table perfectly well: `innerText` reports text as
#: laid out, and the stylesheet upper-cases `th`, so the browser hands back
#: `GENERATED\tTEMPLATE\tFOR\tSTILL CURRENT?\tSIZE`. Anything in this file that
#: reads header text has to go through the same fold.
ROWS = """() => {
  const t = [...document.querySelectorAll('table.findings')].find(
    (el) => (el.tHead ? el.tHead.innerText : '')
      .toUpperCase().includes('STILL CURRENT?'));
  if (!t) return null;
  return [...t.tBodies[0].rows].map((r) => ({
    text: r.innerText,
    verbs: [...r.querySelectorAll('a, button')].map((e) => e.innerText.trim()),
  }));
}"""


#: The same table, asked whether it has grown past `n` rows.
GREW = """(n) => {
  const t = [...document.querySelectorAll('table.findings')].find(
    (el) => (el.tHead ? el.tHead.innerText : '')
      .toUpperCase().includes('STILL CURRENT?'));
  return !!t && t.tBodies[0].rows.length > n;
}"""


def restage(db: str, version) -> list:
    """Rewrite every stored deliverable's renderer version, handing back the old.

    The fixture database is shared with `test_a11y_rendered.py`, so each caller
    restores what it changed.
    """
    conn = sqlite3.connect(db)
    before = conn.execute("SELECT id, renderer_version FROM reports").fetchall()
    assert before, "the fixture stored no deliverable, so no row can be amended"
    conn.execute("UPDATE reports SET renderer_version=?", (version,))
    conn.commit()
    conn.close()
    return before


def restore(db: str, before: list) -> None:
    conn = sqlite3.connect(db)
    for report_id, version in before:
        conn.execute("UPDATE reports SET renderer_version=? WHERE id=?",
                     (version, report_id))
    conn.commit()
    conn.close()


def deliverables(pg, base: str, site: str):
    pg.goto(f"{base}/#/sites/{site}/reports", wait_until="load")
    pg.wait_for_selector(".stats-row", timeout=15_000)
    pg.wait_for_selector("table.findings", timeout=15_000)
    pg.wait_for_timeout(300)
    return pg.evaluate(ROWS)


@live
def test_the_row_that_says_regenerate_offers_a_control_that_does_it(
        served, browser_page):
    """The finding's own sentence, and the verb it has never had beside it.

    NULL is the state the nine recovered client documents are actually in -
    adopted from disk, with no renderer version to record - so that is what is
    staged here rather than a version string chosen to make a branch fire.
    """
    base, ids = served
    before = restage(ids["db"], None)
    try:
        rows = deliverables(browser_page, base, ids["site"])
        assert rows, f"the deliverables table did not render: {rows!r}"
        told = [r for r in rows if "regenerate before sending" in r["text"]]
        assert told, (
            "the screen no longer tells the operator to regenerate, so this "
            f"guard is pointed at the wrong branch: {[r['text'] for r in rows]!r}")
        for row in told:
            assert any(v.lower() == "regenerate" for v in row["verbs"]), (
                "the row states a required action and offers no route to it - "
                f"verbs were {row['verbs']!r} on {row['text']!r}")
    finally:
        restore(ids["db"], before)


@live
def test_a_document_written_by_an_older_renderer_can_be_rewritten_too(
        served, browser_page):
    """`superseded` is the same defect in its commoner spelling.

    Thirteen of the operator's twenty-two stored rows are behind the current
    renderer rather than unknown to it, so guarding only the NULL branch would
    close the finding for nine rows and leave thirteen.
    """
    base, ids = served
    before = restage(ids["db"], "0.0.1")
    try:
        rows = deliverables(browser_page, base, ids["site"])
        assert rows, f"the deliverables table did not render: {rows!r}"
        older = [r for r in rows if "older report renderer" in r["text"]]
        assert older, (
            f"the superseded branch did not paint: {[r['text'] for r in rows]!r}")
        for row in older:
            assert any(v.lower() == "regenerate" for v in row["verbs"]), (
                f"no route to a rewrite: verbs were {row['verbs']!r}")
    finally:
        restore(ids["db"], before)


@live
def test_a_current_document_is_not_offered_a_rewrite_that_would_change_nothing(
        served, browser_page):
    """The negative clause, and the one that keeps this from being UX-39.

    Regenerating against the same runs with the same renderer produces the same
    document under a new id. A control offered where it cannot usefully work is
    its own finding on this project; the verb belongs where the sentence is.
    """
    base, ids = served
    rows = deliverables(browser_page, base, ids["site"])
    assert rows, f"the deliverables table did not render: {rows!r}"
    current = [r for r in rows if "older report renderer" not in r["text"]
               and "regenerate before sending" not in r["text"]]
    assert current, (
        "the fixture holds no deliverable at the current renderer, so this "
        f"clause tested nothing: {[r['text'] for r in rows]!r}")
    for row in current:
        assert not any(v.lower() == "regenerate" for v in row["verbs"]), (
            f"a current document was offered a rewrite: {row['verbs']!r}")


@live
def test_pressing_it_writes_a_new_deliverable_at_the_current_renderer(
        served, browser_page):
    """End to end, read from the register rather than from the screen's own word.

    The row count is checked in `reports` because that is where WF-75's fix put
    the fact: a pass that repaints the table while writing nothing would look
    identical from the browser.
    """
    base, ids = served
    before = restage(ids["db"], None)
    try:
        conn = sqlite3.connect(ids["db"])
        was = conn.execute("SELECT COUNT(1) FROM reports").fetchone()[0]
        conn.close()

        rows = deliverables(browser_page, base, ids["site"])
        assert rows, f"the deliverables table did not render: {rows!r}"
        # Found by the verb's own name rather than by a marker class. A class
        # existing only so a test can select it has to be recorded in
        # `SELECTED_NOT_PAINTED`, and that register carries two open findings
        # of its own about rows going stale in it - so the guard is pointed at
        # the thing it is actually about, which is the word on the control.
        offered = [r for r in rows
                   if any(v.lower() == "regenerate" for v in r["verbs"])]
        assert offered, "no regenerate control to press"
        browser_page.click("table.findings button:has-text('regenerate')")
        # Waited on the table growing rather than on the control
        # disappearing, and still the right thing to wait on. The first
        # version watched the `regen-btn` count fall and would have hung for
        # its whole timeout, because a press left the row it was pressed on
        # completely unchanged. Since Q-9 was answered `supersede` the pressed
        # row does stop offering the control - the clause below measures
        # exactly that - but the row count is still the earlier and
        # unambiguous signal: it moves on the write itself rather than on the
        # reload that follows it.
        browser_page.wait_for_function(GREW, arg=len(rows), timeout=60_000)

        conn = sqlite3.connect(ids["db"])
        now = conn.execute("SELECT COUNT(1) FROM reports").fetchone()[0]
        made = conn.execute(
            "SELECT COUNT(1) FROM reports WHERE renderer_version=?",
            (RENDERER_VERSION,)).fetchone()[0]
        conn.close()
        assert now == was + 1, (
            f"pressing regenerate left the register at {now} rows, was {was}")
        assert made == 1, (
            f"{made} row(s) carry the current renderer version; expected the "
            "one just written")
    finally:
        restore(ids["db"], before)


@live
def test_the_row_that_was_pressed_stops_offering_the_control(
        served, browser_page):
    """WF-91, and `QUESTIONS.md` Q-9's answer read off the screen.

    A press appended a document and left the pressed row exactly as it was, so
    the row kept its `unknown` renderer, kept the sentence asking for a
    regeneration, and kept the button - for ever. Audit 074 measured what that
    costs on the operator's own database: 14 rows offering the control, 11 on
    one site, 9 of them mutually indistinguishable on every column this table
    renders. The operator answered **supersede** on 23 August 2026: the new
    document records which one it replaced, and the replaced row stops being
    asked to do again what has just been done.

    **Counted, not inspected.** Every row is staged to `unknown`, so every row
    offers the control; one press must take exactly one away. A clause that
    only looked for the words "replaced by" would pass on a screen that said
    so and went on offering the button beside it, which is the finding rather
    than its fix. The replaced row is asserted to still be *listed* in the same
    breath, because dropping it would be the delete answer - the one that was
    put to the operator and not chosen.
    """
    base, ids = served
    before = restage(ids["db"], None)
    try:
        rows = deliverables(browser_page, base, ids["site"])
        assert rows, f"the deliverables table did not render: {rows!r}"
        offered = [r for r in rows
                   if any(v.lower() == "regenerate" for v in r["verbs"])]
        assert offered, "no regenerate control to press"

        browser_page.click("table.findings button:has-text('regenerate')")
        browser_page.wait_for_function(GREW, arg=len(rows), timeout=60_000)
        # The table repaints from `load()` after the POST returns, and the row
        # count moves on the write. Given a moment so the reloaded rows are
        # what is read rather than the pre-press ones.
        browser_page.wait_for_timeout(500)

        after = deliverables(browser_page, base, ids["site"])
        assert after, "the deliverables table stopped rendering after a press"
        still = [r for r in after
                 if any(v.lower() == "regenerate" for v in r["verbs"])]
        assert len(still) == len(offered) - 1, (
            "pressing regenerate did not take the control off the row it was "
            f"pressed on: {len(offered)} rows offered it before and "
            f"{len(still)} after, against the {len(offered) - 1} expected. "
            "The document written by the press carries the current renderer "
            "and is never offered one, so the only row that can have changed "
            "is the pressed one.")
        assert len(after) == len(rows) + 1, (
            f"the register went from {len(rows)} rows to {len(after)}; a "
            "supersede adds a row and removes none")
        replaced = [r for r in after if "replaced by" in r["text"]]
        assert replaced, (
            "no row says which document replaced it, so the register cannot "
            f"say which replaced which: {[r['text'] for r in after]!r}")
        assert any("replaces" in r["text"] for r in after), (
            "the new document does not say what it was regenerated from: "
            f"{[r['text'] for r in after]!r}")
        # The instruction is the thing that must stop, and it is a different
        # string from the button. A row still asking to be regenerated while
        # offering no way to do it would be the affordance invariant inverted
        # - which is the founding finding of this whole file.
        for row in replaced:
            assert "regenerate before sending" not in row["text"], (
                "a replaced document still asks to be regenerated before "
                f"sending: {row['text']!r}")
    finally:
        restore(ids["db"], before)


#: The status region this screen is required to carry, read from the DOM rather
#: than from the source. Returns every announced region inside the Deliverables
#: table with the two attributes that make it one, so a region that exists but
#: announces nothing is distinguishable from one that is absent.
STATUS = """() => {
  const t = [...document.querySelectorAll('table.findings')].find(
    (el) => (el.tHead ? el.tHead.innerText : '')
      .toUpperCase().includes('STILL CURRENT?'));
  if (!t) return null;
  return [...t.querySelectorAll('[role="status"]')].map((e) => ({
    text: e.innerText.trim(),
    live: e.getAttribute('aria-live'),
  }));
}"""


#: What the browser actually painted on the control while it was busy - not
#: what the stylesheet declared. `test_dashboard_a11y.py`'s own docstring is
#: the authority for why this has to come from a browser: "Static analysis
#: checks what the author declared; only a browser knows what was painted",
#: written after `.seg-count` shipped at 3.29:1 with every declared pair
#: passing.
PAINT = """() => {
  const t = [...document.querySelectorAll('table.findings')].find(
    (el) => (el.tHead ? el.tHead.innerText : '')
      .toUpperCase().includes('STILL CURRENT?'));
  const b = t && [...t.querySelectorAll('button')].find((e) => e.disabled);
  if (!b) return null;
  const s = getComputedStyle(b);
  return {label: b.innerText.trim(), color: s.color,
          background: s.backgroundColor, opacity: s.opacity};
}"""


def _rgb(value: str) -> str:
    """`rgb(61, 90, 134)` as the `#3d5a86` the contrast helper takes."""
    parts = re.findall(r"[\d.]+", value)
    assert len(parts) >= 3, f"not a colour the browser reports: {value!r}"
    assert len(parts) == 3 or float(parts[3]) == 1.0, (
        f"a translucent paint ({value!r}) is the defect this clause is about "
        "in another spelling - the pair read back is not the pair painted")
    return "#" + "".join(f"{round(float(p)):02x}" for p in parts[:3])


def _press_and_hold(pg, base: str, site: str, handler):
    """Drive the control to its in-flight state and leave it there.

    Routed rather than raced. `test_fetch_state.py:248` holds a route for the
    same reason: an in-flight state observed by pressing and hoping is a state
    the guard reports on when the machine is slow and skips when it is not.
    """
    rows = deliverables(pg, base, site)
    assert rows, f"the deliverables table did not render: {rows!r}"
    assert any(v.lower() == "regenerate" for r in rows for v in r["verbs"]), (
        f"no regenerate control to press: {[r['verbs'] for r in rows]!r}")
    pg.route("**/api/reports", handler)
    pg.click("table.findings button:has-text('regenerate')")
    pg.wait_for_timeout(1200)
    return rows


@live
def test_the_control_announces_that_it_is_working(served, browser_page):
    """UX-64. The only success signal is a row appearing elsewhere in the
    table, and the only in-flight signal is a greyed control - neither of which
    a screen reader is told about.

    The house pattern is four files away and documented: `components.tsx:693`
    renders `role="status" aria-live="polite"` under a comment explaining
    precisely this, written when `Loading` was found to appear with no
    announcement at all. A second consumer of a pattern is what makes it one.
    """
    base, ids = served
    held: list = []
    before = restage(ids["db"], None)
    try:
        _press_and_hold(browser_page, base, ids["site"],
                        lambda route: held.append(route))
        assert held, (
            "the press sent no request, so nothing was in flight and this "
            "clause proves nothing about the state during one")
        regions = browser_page.evaluate(STATUS)
        assert regions is not None, "the deliverables table stopped rendering"
        announced = [r for r in regions if r["live"] == "polite" and r["text"]]
        assert announced, (
            "the control is working and says so to nobody using a screen "
            f"reader - announced regions in the table were {regions!r}")
        assert any("regenerat" in r["text"].lower() for r in announced), (
            "a region is announced but not about this control: "
            f"{[r['text'] for r in announced]!r}")
    finally:
        restore(ids["db"], before)


@live
def test_the_working_control_is_still_legible(served, browser_page):
    """UI-16, read off the pixels rather than off the stylesheet.

    `button:disabled { opacity: 0.5 }` was the product's single in-flight
    indicator, and opacity composites the whole element over its ground - so
    `.pill-btn`'s measured, passing pair painted 2.12:1 in light and 2.85:1 in
    dark. `test_dashboard_a11y.py` cannot see that by construction and its own
    docstring says so; this is the clause that can.

    Asserting `opacity == 1` as well as the ratio is deliberate. With any
    fading in play the two colours `getComputedStyle` hands back are the ones
    that were *declared*, so the ratio computed from them would be the passing
    number the defect hides behind - the check would agree with itself.
    """
    base, ids = served
    held: list = []
    before = restage(ids["db"], None)
    try:
        _press_and_hold(browser_page, base, ids["site"],
                        lambda route: held.append(route))
        assert held, "nothing was in flight, so no control is disabled to read"
        paint = browser_page.evaluate(PAINT)
        assert paint, (
            "no control is disabled while a request is out - the product's "
            "only in-flight indicator did not appear")
        assert paint["opacity"] == "1", (
            f"the busy control is faded to opacity {paint['opacity']}, so what "
            "the operator sees is neither of the colours this stylesheet "
            f"measured: {paint!r}")
        got = contrast(_rgb(paint["color"]), _rgb(paint["background"]))
        assert got >= AA_TEXT, (
            f"the busy control's label {paint['label']!r} painted "
            f"{paint['color']} on {paint['background']} = {got:.2f}:1, "
            f"needs {AA_TEXT}:1")
    finally:
        restore(ids["db"], before)


@live
def test_a_refused_rewrite_is_announced_too(served, browser_page):
    """The other half of UX-64, and the one with a live cause behind it.

    `POST /api/reports` is refused by the honesty gate for two of the four
    sites in the operator's own database (KI-48) and answers 500 with what it
    objected to. The sentence is already rendered - `regenerate()` catches and
    says so on the row rather than swallowing it - and it appears as a bare
    `<div>` that no screen reader is told has arrived.
    """
    base, ids = served
    before = restage(ids["db"], None)
    try:
        _press_and_hold(
            browser_page, base, ids["site"],
            lambda route: route.fulfill(
                status=500, content_type="application/json",
                body='{"detail": "refused by the honesty gate"}'))
        regions = browser_page.evaluate(STATUS)
        assert regions is not None, "the deliverables table stopped rendering"
        said = [r for r in regions
                if r["live"] == "polite" and "could not rewrite" in r["text"]]
        assert said, (
            "the rewrite was refused and the refusal reached no screen "
            f"reader - announced regions were {regions!r}")
    finally:
        restore(ids["db"], before)
